version: '3'
services:
  master:
    image: wuwei:hadoop-namenode
    networks:
      hadoop_cluster:
        aliases:
         - hadoop-master
    ports:
     - "50070:50070"
     - "50090:50090"
     - "8088:8088"
     - "8188:8188"
     - "19888:19888"
     - "10200:10200"
    depends_on:
     - slave1
     - slave2
    tty: true
    stdin_open: true
  slave1:
    image: wuwei:hadoop-datanode
    networks:
      hadoop_cluster:
        aliases:
         - hadoop-slave1
    ports:
     - "50075:50075"
     - "8042:8042"
    tty: true
    stdin_open: true
  slave2:
    image: wuwei:hadoop-datanode
    networks:
      hadoop_cluster:
        aliases:
         - hadoop-slave2
    ports:
     - "50076:50075"
     - "8043:8042"
    tty: true
    stdin_open: true
networks:
  hadoop_cluster:
    driver: bridge
